name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'site/**'
  pull_request:
    branches:
      - main
    paths:
      - 'site/**'
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install
        run: yarn
        working-directory: ./site

      - name: Build
        run: yarn build
        env:
          REACT_APP_NAME: ${{ secrets.REACT_APP_NAME }}
        working-directory: ./site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./site/build
          CLEAN: true
